package com.example.nightjar.ui.studio

/** A General MIDI instrument with display metadata. */
data class GmInstrument(
    val program: Int,
    val name: String,
    val category: String,
    val isCurated: Boolean = false
)

/** Complete General MIDI instrument list (programs 0-127). */
val GM_INSTRUMENTS = listOf(
    // Piano (0-7)
    GmInstrument(0, "Acoustic Grand Piano", "Piano", isCurated = true),
    GmInstrument(1, "Bright Acoustic Piano", "Piano"),
    GmInstrument(2, "Electric Grand Piano", "Piano"),
    GmInstrument(3, "Honky-Tonk Piano", "Piano"),
    GmInstrument(4, "Electric Piano 1", "Keys", isCurated = true),
    GmInstrument(5, "Electric Piano 2", "Keys"),
    GmInstrument(6, "Harpsichord", "Keys"),
    GmInstrument(7, "Clavinet", "Keys", isCurated = true),
    // Chromatic Percussion (8-15)
    GmInstrument(8, "Celesta", "Chromatic Perc"),
    GmInstrument(9, "Glockenspiel", "Chromatic Perc"),
    GmInstrument(10, "Music Box", "Chromatic Perc", isCurated = true),
    GmInstrument(11, "Vibraphone", "Chromatic Perc", isCurated = true),
    GmInstrument(12, "Marimba", "Chromatic Perc"),
    GmInstrument(13, "Xylophone", "Chromatic Perc"),
    GmInstrument(14, "Tubular Bells", "Chromatic Perc"),
    GmInstrument(15, "Dulcimer", "Chromatic Perc"),
    // Organ (16-23)
    GmInstrument(16, "Drawbar Organ", "Organ"),
    GmInstrument(17, "Percussive Organ", "Organ"),
    GmInstrument(18, "Rock Organ", "Organ", isCurated = true),
    GmInstrument(19, "Church Organ", "Organ"),
    GmInstrument(20, "Reed Organ", "Organ"),
    GmInstrument(21, "Accordion", "Organ"),
    GmInstrument(22, "Harmonica", "Organ"),
    GmInstrument(23, "Tango Accordion", "Organ"),
    // Guitar (24-31)
    GmInstrument(24, "Acoustic Guitar (Nylon)", "Guitar", isCurated = true),
    GmInstrument(25, "Acoustic Guitar (Steel)", "Guitar", isCurated = true),
    GmInstrument(26, "Electric Guitar (Jazz)", "Guitar"),
    GmInstrument(27, "Electric Guitar (Clean)", "Guitar", isCurated = true),
    GmInstrument(28, "Electric Guitar (Muted)", "Guitar"),
    GmInstrument(29, "Overdriven Guitar", "Guitar", isCurated = true),
    GmInstrument(30, "Distortion Guitar", "Guitar"),
    GmInstrument(31, "Guitar Harmonics", "Guitar"),
    // Bass (32-39)
    GmInstrument(32, "Acoustic Bass", "Bass", isCurated = true),
    GmInstrument(33, "Electric Bass (Finger)", "Bass", isCurated = true),
    GmInstrument(34, "Electric Bass (Pick)", "Bass"),
    GmInstrument(35, "Fretless Bass", "Bass"),
    GmInstrument(36, "Slap Bass 1", "Bass"),
    GmInstrument(37, "Slap Bass 2", "Bass"),
    GmInstrument(38, "Synth Bass 1", "Bass", isCurated = true),
    GmInstrument(39, "Synth Bass 2", "Bass"),
    // Strings (40-47)
    GmInstrument(40, "Violin", "Strings", isCurated = true),
    GmInstrument(41, "Viola", "Strings"),
    GmInstrument(42, "Cello", "Strings", isCurated = true),
    GmInstrument(43, "Contrabass", "Strings"),
    GmInstrument(44, "Tremolo Strings", "Strings"),
    GmInstrument(45, "Pizzicato Strings", "Strings"),
    GmInstrument(46, "Orchestral Harp", "Strings"),
    GmInstrument(47, "Timpani", "Strings"),
    // Ensemble (48-55)
    GmInstrument(48, "String Ensemble 1", "Ensemble", isCurated = true),
    GmInstrument(49, "String Ensemble 2", "Ensemble"),
    GmInstrument(50, "Synth Strings 1", "Ensemble"),
    GmInstrument(51, "Synth Strings 2", "Ensemble"),
    GmInstrument(52, "Choir Aahs", "Ensemble"),
    GmInstrument(53, "Voice Oohs", "Ensemble"),
    GmInstrument(54, "Synth Choir", "Ensemble"),
    GmInstrument(55, "Orchestra Hit", "Ensemble"),
    // Brass (56-63)
    GmInstrument(56, "Trumpet", "Brass", isCurated = true),
    GmInstrument(57, "Trombone", "Brass"),
    GmInstrument(58, "Tuba", "Brass"),
    GmInstrument(59, "Muted Trumpet", "Brass"),
    GmInstrument(60, "French Horn", "Brass"),
    GmInstrument(61, "Brass Section", "Brass", isCurated = true),
    GmInstrument(62, "Synth Brass 1", "Brass"),
    GmInstrument(63, "Synth Brass 2", "Brass"),
    // Reed (64-71)
    GmInstrument(64, "Soprano Sax", "Woodwind"),
    GmInstrument(65, "Alto Sax", "Woodwind", isCurated = true),
    GmInstrument(66, "Tenor Sax", "Woodwind"),
    GmInstrument(67, "Baritone Sax", "Woodwind"),
    GmInstrument(68, "Oboe", "Woodwind"),
    GmInstrument(69, "English Horn", "Woodwind"),
    GmInstrument(70, "Bassoon", "Woodwind"),
    GmInstrument(71, "Clarinet", "Woodwind"),
    // Pipe (72-79)
    GmInstrument(72, "Piccolo", "Pipe"),
    GmInstrument(73, "Flute", "Pipe", isCurated = true),
    GmInstrument(74, "Recorder", "Pipe"),
    GmInstrument(75, "Pan Flute", "Pipe"),
    GmInstrument(76, "Blown Bottle", "Pipe"),
    GmInstrument(77, "Shakuhachi", "Pipe"),
    GmInstrument(78, "Whistle", "Pipe"),
    GmInstrument(79, "Ocarina", "Pipe"),
    // Synth Lead (80-87)
    GmInstrument(80, "Lead 1 (Square)", "Synth", isCurated = true),
    GmInstrument(81, "Lead 2 (Sawtooth)", "Synth", isCurated = true),
    GmInstrument(82, "Lead 3 (Calliope)", "Synth"),
    GmInstrument(83, "Lead 4 (Chiff)", "Synth"),
    GmInstrument(84, "Lead 5 (Charang)", "Synth"),
    GmInstrument(85, "Lead 6 (Voice)", "Synth"),
    GmInstrument(86, "Lead 7 (Fifths)", "Synth"),
    GmInstrument(87, "Lead 8 (Bass + Lead)", "Synth"),
    // Synth Pad (88-95)
    GmInstrument(88, "Pad 1 (New Age)", "Pads", isCurated = true),
    GmInstrument(89, "Pad 2 (Warm)", "Pads", isCurated = true),
    GmInstrument(90, "Pad 3 (Polysynth)", "Pads"),
    GmInstrument(91, "Pad 4 (Choir)", "Pads"),
    GmInstrument(92, "Pad 5 (Bowed)", "Pads"),
    GmInstrument(93, "Pad 6 (Metallic)", "Pads"),
    GmInstrument(94, "Pad 7 (Halo)", "Pads"),
    GmInstrument(95, "Pad 8 (Sweep)", "Pads"),
    // Synth Effects (96-103)
    GmInstrument(96, "FX 1 (Rain)", "Sound Effects"),
    GmInstrument(97, "FX 2 (Soundtrack)", "Sound Effects"),
    GmInstrument(98, "FX 3 (Crystal)", "Sound Effects"),
    GmInstrument(99, "FX 4 (Atmosphere)", "Sound Effects"),
    GmInstrument(100, "FX 5 (Brightness)", "Sound Effects"),
    GmInstrument(101, "FX 6 (Goblins)", "Sound Effects"),
    GmInstrument(102, "FX 7 (Echoes)", "Sound Effects"),
    GmInstrument(103, "FX 8 (Sci-Fi)", "Sound Effects"),
    // Ethnic (104-111)
    GmInstrument(104, "Sitar", "Ethnic"),
    GmInstrument(105, "Banjo", "Ethnic"),
    GmInstrument(106, "Shamisen", "Ethnic"),
    GmInstrument(107, "Koto", "Ethnic"),
    GmInstrument(108, "Kalimba", "Ethnic"),
    GmInstrument(109, "Bagpipe", "Ethnic"),
    GmInstrument(110, "Fiddle", "Ethnic"),
    GmInstrument(111, "Shanai", "Ethnic"),
    // Percussive (112-119)
    GmInstrument(112, "Tinkle Bell", "Percussive"),
    GmInstrument(113, "Agogo", "Percussive"),
    GmInstrument(114, "Steel Drums", "Percussive"),
    GmInstrument(115, "Woodblock", "Percussive"),
    GmInstrument(116, "Taiko Drum", "Percussive"),
    GmInstrument(117, "Melodic Tom", "Percussive"),
    GmInstrument(118, "Synth Drum", "Percussive"),
    GmInstrument(119, "Reverse Cymbal", "Percussive"),
    // Sound Effects (120-127)
    GmInstrument(120, "Guitar Fret Noise", "Sound Effects"),
    GmInstrument(121, "Breath Noise", "Sound Effects"),
    GmInstrument(122, "Seashore", "Sound Effects"),
    GmInstrument(123, "Bird Tweet", "Sound Effects"),
    GmInstrument(124, "Telephone Ring", "Sound Effects"),
    GmInstrument(125, "Helicopter", "Sound Effects"),
    GmInstrument(126, "Applause", "Sound Effects"),
    GmInstrument(127, "Gunshot", "Sound Effects")
)

/** Look up a GM instrument long-form name by program number. */
fun gmInstrumentName(program: Int): String =
    GM_INSTRUMENTS.getOrNull(program)?.name ?: "Program $program"
