#pragma once

#include "step_sequencer.h"  // for NoteEvent
#include <atomic>
#include <cstdint>
#include <functional>
#include <mutex>
#include <vector>

namespace nightjar {

/**
 * A single MIDI event at a specific frame position.
 * Pre-generated by Kotlin as paired noteOn/noteOff events sorted by frame.
 */
struct MidiEvent {
    int64_t framePos;   // absolute timeline frame position
    int channel;        // MIDI channel (0-15)
    int note;           // MIDI note number (0-127)
    int velocity;       // > 0 = noteOn, 0 = noteOff
};

/**
 * All MIDI events and metadata for a single instrument track.
 */
struct MidiTrackData {
    int channel = 0;        // MIDI channel for this track
    int program = 0;        // GM program number (0-127)
    float volume = 1.0f;    // Track volume multiplier
    bool muted = false;
    std::vector<MidiEvent> events;   // sorted by framePos
};

/**
 * Sequencer that plays variable-length MIDI note events across multiple
 * instrument channels. Events are pre-generated as noteOn/noteOff pairs
 * sorted by frame position.
 *
 * Uses the same double-buffered, lock-free-read architecture as StepSequencer:
 * UI writes to the inactive buffer under a mutex, then atomically swaps.
 * The render thread reads lock-free from the active buffer.
 *
 * tick() is called from SynthEngine's render thread between render chunks.
 * It returns NoteEvent structs (same type as StepSequencer) for the caller
 * to fire into FluidSynth.
 */
class MidiSequencer {
public:
    MidiSequencer();

    /**
     * Replace all MIDI track data. Called from UI thread (JNI).
     * Mutex-protected, writes to inactive buffer, then swaps.
     */
    void updateTracks(const std::vector<MidiTrackData>& tracks);

    /**
     * Advance the sequencer and return note events for this chunk.
     * Called from the render thread -- lock-free read of active data.
     *
     * @param renderPos   Current render position in frames (global timeline).
     * @param chunkFrames Number of frames in this render chunk.
     * @return Reference to internal event buffer (valid until next tick).
     */
    const std::vector<NoteEvent>& tick(int64_t renderPos, int32_t chunkFrames);

    /**
     * Reset playback state. On seek, uses binary search to find the correct
     * event index for the new position.
     */
    void reset();

    /**
     * Reset to a specific position (used on seek).
     * Binary-searches each track's events to find the correct starting index.
     */
    void resetToPosition(int64_t posFrames);

    /**
     * Get the maximum end frame across all MIDI tracks.
     * Used by AudioEngine to determine total timeline length.
     */
    int64_t getMaxEndFrame() const;

    /**
     * Snapshot the current per-track (channel, program) assignments.
     * Render-thread-callable lock-free read of the active snapshot. Used
     * by SynthEngine to re-issue program changes on flush / play /
     * loop-wrap so the first noteOn after a transport transition lands
     * at the correct preset.
     */
    void forEachProgramAssignment(
        const std::function<void(int channel, int program)>& fn) const;

private:
    /**
     * Snapshot of all MIDI tracks. Double-buffered for lock-free reads.
     *
     * `generation` is bumped by every updateTracks() call so the render
     * thread can detect a swap and re-align its per-track cursors to
     * the current render frame. Without this, a mid-playback edit would
     * land cursors at index 0 while renderPos has advanced, and the
     * tick() guard at framePos >= renderPos would silently consume
     * every event before the playhead -- new content placed in the
     * already-played region of the timeline never gets fired on the
     * next loop pass.
     */
    struct Snapshot {
        std::vector<MidiTrackData> tracks;
        std::vector<size_t> nextEventIndex;  // per-track cursor
        uint64_t generation = 0;
    };

    Snapshot snapshotA_, snapshotB_;
    std::atomic<Snapshot*> active_{&snapshotA_};
    std::mutex editMutex_;
    /** Monotonic counter incremented by updateTracks(). The next-issued
     *  snapshot copies this into its `generation` before the atomic
     *  swap. Render thread reads `active->generation` and compares to
     *  [lastSeenGeneration_]. */
    uint64_t generationCounter_ = 0;
    /** Render-thread-local: the generation last observed during tick().
     *  On a swap (mismatch), the render thread re-aligns cursors via
     *  resetToPosition before iterating events. */
    uint64_t lastSeenGeneration_ = 0;

    std::vector<NoteEvent> pendingEvents_;

    // Bitmask of channels that need all-notes-off (set by updateTracks, consumed by tick)
    std::atomic<uint16_t> silenceChannelMask_{0};
};

}  // namespace nightjar
