#pragma once

#include "step_sequencer.h"  // for NoteEvent
#include <atomic>
#include <cstdint>
#include <mutex>
#include <vector>

namespace nightjar {

/**
 * A single MIDI event at a specific frame position.
 * Pre-generated by Kotlin as paired noteOn/noteOff events sorted by frame.
 */
struct MidiEvent {
    int64_t framePos;   // absolute timeline frame position
    int channel;        // MIDI channel (0-15)
    int note;           // MIDI note number (0-127)
    int velocity;       // > 0 = noteOn, 0 = noteOff
};

/**
 * All MIDI events and metadata for a single instrument track.
 */
struct MidiTrackData {
    int channel = 0;        // MIDI channel for this track
    int program = 0;        // GM program number (0-127)
    float volume = 1.0f;    // Track volume multiplier
    bool muted = false;
    std::vector<MidiEvent> events;   // sorted by framePos
};

/**
 * Sequencer that plays variable-length MIDI note events across multiple
 * instrument channels. Events are pre-generated as noteOn/noteOff pairs
 * sorted by frame position.
 *
 * Uses the same double-buffered, lock-free-read architecture as StepSequencer:
 * UI writes to the inactive buffer under a mutex, then atomically swaps.
 * The render thread reads lock-free from the active buffer.
 *
 * tick() is called from SynthEngine's render thread between render chunks.
 * It returns NoteEvent structs (same type as StepSequencer) for the caller
 * to fire into FluidSynth.
 */
class MidiSequencer {
public:
    MidiSequencer();

    /**
     * Replace all MIDI track data. Called from UI thread (JNI).
     * Mutex-protected, writes to inactive buffer, then swaps.
     */
    void updateTracks(const std::vector<MidiTrackData>& tracks);

    /**
     * Advance the sequencer and return note events for this chunk.
     * Called from the render thread -- lock-free read of active data.
     *
     * @param renderPos   Current render position in frames (global timeline).
     * @param chunkFrames Number of frames in this render chunk.
     * @return Reference to internal event buffer (valid until next tick).
     */
    const std::vector<NoteEvent>& tick(int64_t renderPos, int32_t chunkFrames);

    /**
     * Reset playback state. On seek, uses binary search to find the correct
     * event index for the new position.
     */
    void reset();

    /**
     * Reset to a specific position (used on seek).
     * Binary-searches each track's events to find the correct starting index.
     */
    void resetToPosition(int64_t posFrames);

    /**
     * Get the maximum end frame across all MIDI tracks.
     * Used by AudioEngine to determine total timeline length.
     */
    int64_t getMaxEndFrame() const;

private:
    /**
     * Snapshot of all MIDI tracks. Double-buffered for lock-free reads.
     */
    struct Snapshot {
        std::vector<MidiTrackData> tracks;
        std::vector<size_t> nextEventIndex;  // per-track cursor
    };

    Snapshot snapshotA_, snapshotB_;
    std::atomic<Snapshot*> active_{&snapshotA_};
    std::mutex editMutex_;

    std::vector<NoteEvent> pendingEvents_;
};

}  // namespace nightjar
